parameters:
#    bb_main.example.class: mwd\BowlingBuddyBundle\Example

services:
#    bb_main.example:
#        class: %bb_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
